CONNECTION=USB
RIGCTLD_HOST=127.0.0.1
RIGCTLD_PORT=4532
MFG=Yaesu
MODEL=FTDX-10
RIG_MODEL=1042
SERIAL_PORT=/dev/cu.usbserial-1330
BAUD_RATE=38400
DATA_BITS=8
PARITY=NONE
STOP_BITS=2
FLOW_CONTROL=NONE
SCAN_SP=0.2
RF_POWER_RANGE=100
OPERATING_MODE=Normal
RF_REFERENCE=0.250
ALC_REFERENCE=0.312
FNC1=VFO_CHG,BD0;
FNC2=TUN_INT,EX0301050;
FNC3=TUN_FC4,EX0301051;
FNC4=TUN_ATA,EX0301052;
WINDOW_X=48
WINDOW_Y=59
